### ISSUE TITLE
issue with server_url

### ISSUE THREAD

**Issue by jerowe** [Egregors/teamcity-docker-compose#2]
Thanks for the great project! I think this is something I am not getting as opposed to an actual issue, but no matter what I try I can't get the agent to bind to the server.

I've tried the hostname of my host, and the IP address from docker0.

```
teamcity-agent_1   | [2017-02-10 12:52:18,052]   WARN - buildServer.AGENT.registration - Error registering on the server via URL http://jillian-computer:8111. Will continue repeating connection attempts. 
```

**Comment by egregors** [comment]
Hi @jerowe, thanks for good words. 

If your agent full warning looks like: 

```
WARN - buildServer.AGENT.registration - Error registering on the server via URL http://teamcity-server:8111. Will continue repeating connection attempts. Details: server is in a maintenance mode
```

it's means TC server in maintenance mode and not ready yet. You should make minimal setup (select database, accept user agreement, create root user) and then agents will connect to the server.

Logs must looks like: 
[teamcity_normal_log.txt](https://github.com/Egregors/teamcity-docker-compose/files/767004/teamcity_normal_log.txt)

You shouldn't change default `SERVER_URL` value from `.env`, because it's just docker-compose service name (`teamcity-server`) with needed port (`8111`), not your real hostname.

I hope, it will useful for you :)
